/**
 * @file
 * This is the main server entry point.
 *
 * It is used to build the project initially; afterwards, the client code hydrates
 * the code generated by this file.
 *
 * You shouldn't need to mess with it, generally.
 */

import React from 'react';
import { renderToString } from 'react-dom/server';
import { HelmetProvider } from 'react-helmet-async';
import App from '../client/app';

export default (context) => {
  const helmetCtx = {};
  const app = renderToString(
    <HelmetProvider context={helmetCtx}>
      <App {...context} />
    </HelmetProvider>,
  );

  const { helmet } = helmetCtx;

  return `
    <!doctype html>
    <html ${helmet.htmlAttributes.toString()}>
      <head>
            ${helmet.title.toString()}
            ${helmet.meta.toString()}
            ${helmet.link.toString()}
      </head>
      <body ${helmet.bodyAttributes.toString()}>
          <div id="app">
            ${app}
          </div>
      </body>
    </html>
  `.trim();
};
